# Generated by Django 5.2.8 on 2025-12-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_dob_user_gender_user_phone_user_rank'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'gd_munsi')), fields=('admin',), name='one_gd_per_admin'),
        ),
    ]
