# Generated by Django 5.2.8 on 2026-01-08 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_personnel', models.PositiveIntegerField(default=0)),
                ('personnel_by_rank', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='security_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'admin')},
            },
        ),
    ]
