# Generated by Django 5.2.8 on 2026-01-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_securitycategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('master_admin', 'Master Admin'), ('super_admin', 'Super Admin'), ('admin', 'Admin'), ('gd_munsi', 'GD Munsi'), ('field_staff', 'Field Staff'), ('vvip', 'VVIP')], max_length=20),
        ),
    ]
