# Generated by Django 5.2.8 on 2026-02-13 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VVIPDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role': 'gd_munsi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gd_assigned_duties', to=settings.AUTH_USER_MODEL)),
                ('field_staff', models.ForeignKey(limit_choices_to={'role': 'field_staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_duties', to=settings.AUTH_USER_MODEL)),
                ('vvip', models.ForeignKey(limit_choices_to={'role': 'vvip'}, on_delete=django.db.models.deletion.CASCADE, related_name='duties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('vvip', 'field_staff', 'is_active')},
            },
        ),
    ]
