# Generated by Django 5.2.8 on 2026-02-13 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_vvipduty'),
    ]

    operations = [
        migrations.AddField(
            model_name='vvipduty',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duties', to='app.securitycategory'),
        ),
    ]
