# Generated by Django 5.2.8 on 2026-02-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_vvipduty_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vvipduty',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='vvipduty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('vvip', 'field_staff'), name='unique_active_vvip_fieldstaff'),
        ),
    ]
