# Generated by Django 5.2.8 on 2026-02-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_vvipduty_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vvipduty',
            name='duty_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vvipduty',
            name='duty_type',
            field=models.CharField(choices=[('static', 'Static'), ('escort', 'Escort'), ('event', 'Event')], default='static', max_length=20),
        ),
        migrations.AddField(
            model_name='vvipduty',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vvipduty',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vvipduty',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vvipduty',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
