# Generated by Django 5.2.8 on 2026-02-16 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_vvipduty_duty_place_vvipduty_duty_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vvipduty',
            name='batch_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
