# Generated by Django 5.2.8 on 2026-02-16 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_vvipduty_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vvipduty',
            name='end_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vvipduty',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vvipduty',
            name='ended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_duties', to=settings.AUTH_USER_MODEL),
        ),
    ]
