# Generated by Django 5.2.8 on 2026-02-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_fieldstaffrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldstaffrequest',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fieldstaffrequest',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
