# Generated by Django 5.2.8 on 2026-02-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_fcmtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtoken',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
