# Generated by Django 5.2.8 on 2026-02-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_fcmtoken_browser_fcmtoken_device_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='device_name',
            field=models.CharField(default='unknown_device', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together={('user', 'device_name')},
        ),
    ]
