# Generated by Django 5.2.8 on 2026-02-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_fcmtoken_device_name_alter_fcmtoken_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
