# Generated by Django 5.2.8 on 2026-02-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_fcmtoken_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.TextField(unique=True),
        ),
    ]
