# Generated by Django 5.2.8 on 2026-02-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_fcmtoken_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together=set(),
        ),
    ]
