# Generated by Django 5.2.8 on 2026-03-02 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_passwordresetotp_attempts_passwordresetotp_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('request_status', 'Request Status'), ('duty_assigned', 'Duty Assigned'), ('duty_ended', 'Duty Ended'), ('system_alert', 'System Alert')], max_length=30)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_model', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='app_notific_user_id_3dfd65_idx')],
            },
        ),
    ]
