# Generated by Django 5.2.8 on 2026-03-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_notification_deleted_at_notification_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldstaffrequest',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='fieldstaffrequest',
            name='request_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='fieldstaffrequest',
            unique_together={('staff', 'request_number')},
        ),
    ]
