# Generated by Django 5.2.8 on 2026-03-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_centralizednotifylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralizednotifylog',
            name='recipients',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
