# Generated by Django 5.2.8 on 2026-03-10 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_centralizednotifylog_recipients'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='app_notific_user_id_3dfd65_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='app_notific_user_id_f49e55_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='app_notific_user_id_a0c8d6_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centralized_notifications_receive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='centralizednotifylog',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centralized_notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request_status', 'Request Status'), ('duty_assigned', 'Duty Assigned'), ('duty_ended', 'Duty Ended'), ('system_alert', 'System Alert'), ('centralized', 'Centralized Notification')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'is_read'], name='app_notific_receive_520b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'created_at'], name='app_notific_receive_d56605_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'is_deleted'], name='app_notific_receive_4777f7_idx'),
        ),
    ]
