# Generated by Django 5.2.8 on 2026-03-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_notification_app_notific_user_id_3dfd65_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request_status', 'Request Status'), ('request', 'Staff Request'), ('duty_assigned', 'Duty Assigned'), ('duty_ended', 'Duty Ended'), ('system_alert', 'System Alert'), ('centralized', 'Centralized Notification')], max_length=30),
        ),
    ]
