# Generated by Django 5.2.8 on 2026-03-18 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_user_email_verified_user_email_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VVIPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_vvip_requests', to=settings.AUTH_USER_MODEL)),
                ('vvip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vvip_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('vvip', 'request_number')},
            },
        ),
    ]
