# Generated by Django 5.2.8 on 2026-03-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_vviprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vvipduty',
            name='geo_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vvipduty',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vvipduty',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vvipduty',
            name='radius',
            field=models.IntegerField(default=100),
        ),
    ]
