# Generated by Django 5.2.8 on 2026-03-19 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_vvipduty_geo_enabled_vvipduty_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('is_inside', models.BooleanField(default=False)),
                ('last_location_lat', models.FloatField(blank=True, null=True)),
                ('last_location_lng', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='app.vvipduty')),
                ('staff', models.ForeignKey(limit_choices_to={'role': 'field_staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='duty_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('staff', 'duty')},
            },
        ),
    ]
