# Generated by Django 5.2.8 on 2026-03-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_dutyattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='vvipduty',
            name='vvip_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vvipduty',
            name='vvip_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
