# Generated by Django 5.2.8 on 2026-03-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_verifyemailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
