# Generated by Django 5.2.8 on 2026-04-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_fcmtoken_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralizednotifylog',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fieldstaffrequest',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vviprequest',
            name='subject',
            field=models.TextField(),
        ),
    ]
